import type { Metadata } from "next";
import "./globals.css";
import Thirdweb from "@/providers/Thirdweb";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Naz Challenge",
  description: "Generated by Pags",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="background-image">
        <Toaster />
        <Thirdweb>{children}</Thirdweb>
      </body>
    </html>
  );
}
